version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb  # 数据库密码
    volumes:
      - "D:/Documents/blockmir3/Nakama/docker/postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"  # 暴露PostgreSQL端口
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5

  # nakama:
  #   container_name: nakama
  #   image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
  #   entrypoint:
  #     - "/bin/sh"
  #     - "-ecx"
  #     - >
  #       /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
  #       exec /nakama/nakama --name nakama1 --database.address postgres:localdb@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200 --runtime.path /nakama/data/modules
  #   restart: always
  #   depends_on:
  #     postgres:
  #       condition: service_healthy  # 等待PostgreSQL健康检查通过
  #   volumes:
  #     - "D:/Documents/blockmir3/Nakama/docker/nakama_data:/nakama/data"  # ⚠️ 替换为你的Windows路径
  #     - "D:/Documents/blockmir3/Nakama/docker/server_modules:/nakama/data/modules"
  #   ports:
  #     - "7349:7349"  # Nakama控制台端口
  #     - "7350:7350"  # 客户端通信端口
  #     - "7351:7351"  # gRPC端口
  #   healthcheck:
  #     test: ["CMD", "/nakama/nakama", "healthcheck"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
